env:
  browser: true
  es2021: true

extends: airbnb-base

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-underscore-dangle:
    - error
    - allow:
        - '__filename'
        - '__dirname'
  import/extensions:
    - error
    - js: always
  import/no-named-as-default: off
  import/no-named-as-default-member: off
  no-console: off
  import/no-extraneous-dependencies: off